apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: pod-delete
  namespace: litmus
spec:
  appinfo:
    appns: chaos-app
    applabel: "app=server"
    appkind: deployment
  jobCleanUpPolicy: delete
  monitoring: false
  annotationCheck: "true"
  engineState: "active"
  chaosServiceAccount: litmus-admin
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "30"
            - name: CHAOS_INTERVAL
              value: "5"
            - name: FORCE
              value: "false"
