apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-framework-sa
  labels:
    app: chaos-framework
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-framework-cr
  labels:
    app: chaos-framework
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-framework-crb
  labels:
    app: chaos-framework
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaos-framework-cr
subjects:
  - kind: ServiceAccount
    name: chaos-framework-sa
    namespace: "{{ .Namespace }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
spec:
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      serviceAccountName: chaos-framework-sa
      containers:
        - name: scheduler
          image: "{{ .Image }}"
          ports:
            - name: web
              containerPort: 8811
          resources:
            limits:
              cpu: "100m"
              memory: "64M"
          env:
            # Infrastructure.
            - name: ARGO_SERVER
              value: argo-server.argo.svc:2746
            - name: STAGE_MONITOR_IMAGE
              value: iskorotkov/chaos-monitor:v0.7.0
            - name: DEVELOPMENT
              value: "true"

            # Target.
            - name: APP_NS
              value: "{{ .AppNS }}"
            - name: CHAOS_NS
              value: "{{ .ChaosNS }}"
            - name: APP_LABEL
              value: app

            # Workflow.
            - name: STAGE_DURATION
              value: 30s
            - name: STAGE_INTERVAL
              value: 30s

            # Node.
            - name: NODE_CPU_HOG_CORES
              value: "1"
            - name: NODE_MEMORY_HOG_PERCENTAGE
              value: "50"
            - name: NODE_IO_STRESS_PERCENTAGE
              value: "90"

            # Pod.
            - name: POD_IO_STRESS_PERCENTAGE
              value: "90"

            # Container.
            - name: CONTAINER_CPU_HOG_CORES
              value: "1"
            - name: CONTAINER_MEMORY_HOG_MB
              value: "1000"

            # Deployment part.
            - name: DEPLOYMENT_PART_PODS_PERCENTAGE
              value: "50"

            # Severity.
            - name: LIGHT_SEVERITY_PERCENTAGE
              value: "30"
            - name: SEVERE_SEVERITY_PERCENTAGE
              value: "90"

            # Latency.
            - name: LIGHT_NETWORK_LATENCY_MS
              value: "1000"
            - name: SEVERE_NETWORK_LATENCY_MS
              value: "9000"

            # Pod delete.
            - name: POD_DELETE_INTERVAL
              value: "5"
            - name: POD_DELETE_FORCE
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler
spec:
  selector:
    app: scheduler
  ports:
    - name: web
      port: 8811
      targetPort: 8811
      protocol: TCP
  type: LoadBalancer
